### ISSUE TITLE
set exit code

### ISSUE THREAD

**Issue by sgratzl** [undefx/py3tester#1]
for continuous integration it would be useful if the tool sets the proper exit codes depending on whether all tests have passed or some has failed.

**Comment by undefx** [comment]
thanks for the suggestion!

this use-case sounds reasonable to me, however i'd prefer not to return a failing exit code _by default_ since there may be some ambiguity around failure of the tool itself versus failure of tests.

what do you think about adding a new command-line flag which would cause exit status to be nonzero for failed tests?

for example, maybe something like:

> python3 -m py3tester.src.py3tester --color --full **--use-exit-code** repo/test/dir/test_module.py

**Comment by sgratzl** [comment]
sounds good

**Comment by undefx** [comment]
[done](https://github.com/undefx/py3tester/commit/906906dfc8b7feb845b9602ea48cc8f5dddd3065)! the flag name is `--use-exit-code`. let me know if you run into any problems.
